### ISSUE TITLE
Project has moved to github and fixed Python 3 support

### ISSUE THREAD

**Issue by iskur** [conda-forge/wmctrl-feedstock#6]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

This wmctrl is an outdated version that does not work under python 3.
The author has moved wmctrl from bitbucket to github and fixed the issue there:

https://github.com/antocuni/wmctrl

Below is an example with the pdbpp-debugger, which made me aware of the problem.

```
$ conda create --name wmctrl
$ conda activate wmctrl
$ conda install pdbpp -c conda-forge
```

```
$ python
Python 3.9.1 (default, Dec 11 2020, 14:32:07) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdb
>>> pdb.set_trace()
--Return--
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dirk/anaconda/envs/wmctrl/lib/python3.9/bdb.py", line 92, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/home/dirk/anaconda/envs/wmctrl/lib/python3.9/bdb.py", line 151, in dispatch_return
    self.user_return(frame, arg)
  File "/home/dirk/anaconda/envs/wmctrl/lib/python3.9/pdb.py", line 294, in user_return
    self.interaction(frame, None)
  File "/home/dirk/anaconda/envs/wmctrl/lib/python3.9/site-packages/pdb.py", line 223, in interaction
    self.exec_if_unfocused()
  File "/home/dirk/anaconda/envs/wmctrl/lib/python3.9/site-packages/pdb.py", line 253, in exec_if_unfocused
    active_win = wmctrl.Window.get_active()
  File "/home/dirk/anaconda/envs/wmctrl/lib/python3.9/site-packages/wmctrl.py", line 56, in get_active
    lst = cls.by_id(id)
  File "/home/dirk/anaconda/envs/wmctrl/lib/python3.9/site-packages/wmctrl.py", line 46, in by_id
    return [win for win in cls.list() if int(win.id, 16) == id]
  File "/home/dirk/anaconda/envs/wmctrl/lib/python3.9/site-packages/wmctrl.py", line 19, in list
    parts[1:7] = map(int, parts[1:7])
TypeError: 'map' object is not subscriptable
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/dirk/anaconda/envs/wmctrl:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py39hf3d152e_1    conda-forge
fancycompleter            0.9.1           py39hde42818_1002    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.2                  he6710b0_1  
openssl                   1.1.1i               h27cfd23_0  
pdbpp                     0.10.0                     py_0    conda-forge
pip                       20.3.3           py39h06a4308_0  
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pyrepl                    0.9.0            py39h07f9747_2    conda-forge
python                    3.9.1                hdb3f193_2  
python_abi                3.9                      1_cp39    conda-forge
readline                  8.1                  h27cfd23_0  
setuptools                52.0.0           py39h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tzdata                    2020f                h52ac0ba_0  
wheel                     0.36.2             pyhd3eb1b0_0  
wmctrl                    0.3                        py_0    conda-forge
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : wmctrl
    active env location : /home/dirk/anaconda/envs/wmctrl
            shell level : 1
       user config file : /home/dirk/.condarc
 populated config files : /home/dirk/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __glibc=2.32=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/dirk/anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dirk/anaconda/pkgs
                          /home/dirk/.conda/pkgs
       envs directories : /home/dirk/anaconda/envs
                          /home/dirk/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.7.7 Linux/5.10.13-arch1-1 arch/rolling glibc/2.32
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by kynan** [comment]
That does not help unfortunately as the author has not tagged a new release of wmctrl and published on PyPI, so there isn't really anything I can do. It's strongly discouraged to build conda packages from HEAD.

Have filed antocuni/wmctrl#6

**Comment by kynan** [comment]
The author has published a new release. Updating the conda-forge package momentarily.

**Comment by ehfd** [comment]
@kynan What is the difference between this project and https://github.com/Conservatory/wmctrl, which is the default `wmctrl` for various OS distros?

**Comment by kynan** [comment]
@ehfd This package is a Python wrapper around the `wmctrl` CLI, see https://github.com/antocuni/wmctrl.

**Comment by ehfd** [comment]
So I would need to make a new recipe if I were to package the CLI?

**Comment by kynan** [comment]
Yep, that's correct.
